version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: adm123
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - db_network
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8001:8080/tcp
    environment: 
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adm123
    networks:
      - db_network
    tty: true

volumes:
  db-data:

networks: 
  db_network:
    driver: bridge